import type { LucideIcon } from "lucide-react";
import {
  Accessibility,
  Brain,
  DollarSign,
  Eye,
  Globe,
  Handshake,
  Heart,
  Mic,
  MessageCircle,
  Shield,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Volume2,
  Wand2,
  Zap,
  Layers,
  Workflow,
  Wrench,
  BookOpen,
  Film,
  Image,
  LayoutGrid,
  Map,
  Flag,
  BadgeCheck,
  Scan,
  BarChart3,
  Lightbulb,
  Network,
  Calendar,
  Database,
  Megaphone,
  PenTool,
  Radar,
  Gauge,
  FlaskConical,
  MousePointerClick,
  Bot,
  GitBranch,
  RefreshCcw,
  MicVocal,
  Repeat2,
  Video,
  Camera,
  SlidersHorizontal,
  MapPin,
  Languages,
  ShieldCheck,
  ShieldAlert,
  TrendingDown,
  LineChart,
  Newspaper,
  SquareStack,
  Thermometer,
  HardDrive,
} from "lucide-react";

export type AiToolRunner = "custom" | "generic";

export interface AiToolDefinition {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  icon: LucideIcon;
  href: string;
  badge?: "New" | "Hot" | "Pro" | "Popular";
  modelLabel?: string;
  runner: AiToolRunner;
  functionName?: string;
  primaryField?: string;
  placeholder?: string;
}

const base = "google/gemini-2.5";

export const aiToolsCatalog: AiToolDefinition[] = [
  // ===== LAYER 1: Core Reasoning =====
  {
    id: "reasoning",
    slug: "reasoning",
    title: "AI Reasoning Engine",
    description: "Multi-step strategic analysis with chain-of-thought logic for complex content decisions.",
    category: "Core Reasoning",
    icon: Brain,
    href: "/ai/reasoning",
    badge: "Pro",
    modelLabel: `${base}-flash / pro`,
    runner: "custom",
  },
  {
    id: "performance-reasoner",
    slug: "performance-reasoner",
    title: "Performance Explainer",
    description: "Diagnose exactly why a post succeeded or failed with causal attribution analysis.",
    category: "Core Reasoning",
    icon: LineChart,
    href: "/ai/performance-reasoner",
    modelLabel: `${base}-pro`,
    runner: "generic",
    functionName: "ai-performance-reasoner",
    primaryField: "content",
    placeholder: "Paste your post text + its metrics (views, likes, shares, comments)…",
  },
  {
    id: "engagement-reasoner",
    slug: "engagement-reasoner",
    title: "Engagement Decoder",
    description: "Map engagement drivers to audience psychology — understand what resonates and why.",
    category: "Core Reasoning",
    icon: Radar,
    href: "/ai/engagement-reasoner",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-engagement-reasoner",
    primaryField: "content",
    placeholder: "Paste content + optional engagement data to decode what's driving interaction…",
  },

  // ===== LAYER 2: Text-to-Text Content =====
  {
    id: "viral-hooks",
    slug: "hooks",
    title: "Viral Hook Generator",
    description: "Craft scroll-stopping opening lines using 10 proven psychological hook frameworks.",
    category: "Content Creation",
    icon: Zap,
    href: "/ai/hooks",
    badge: "Hot",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "hook-lab",
    slug: "hook-lab",
    title: "Hook A/B Lab",
    description: "Generate 10+ hook variations with psychology breakdowns and platform scores for split testing.",
    category: "Content Creation",
    icon: FlaskConical,
    href: "/ai/hook-lab",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-hook-lab",
    primaryField: "topic",
    placeholder: "What is your post/video about? Include niche and audience for better hooks…",
  },
  {
    id: "brand-voice",
    slug: "brand-voice",
    title: "Brand Voice Studio",
    description: "Train AI on your brand's tone, vocabulary, and style to generate on-brand content.",
    category: "Brand Identity",
    icon: Sparkles,
    href: "/ai/brand-voice",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "tone-personality",
    slug: "tone-personality",
    title: "Voice Transformer",
    description: "Rewrite any content in 11 distinct personality modes — from Gen Z slang to luxury editorial.",
    category: "Brand Identity",
    icon: PenTool,
    href: "/ai/tone-personality",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-tone-personality",
    primaryField: "content",
    placeholder: "Paste content to transform. Select personality in advanced options…",
  },
  {
    id: "audience-writer",
    slug: "audience-writer",
    title: "Audience Tailor",
    description: "Rewrite content specifically for a defined audience segment — adjust complexity, references, and tone.",
    category: "Audience Targeting",
    icon: Users,
    href: "/ai/audience-writer",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-audience-writer",
    primaryField: "content",
    placeholder: "Paste content + describe your target audience in advanced options…",
  },
  {
    id: "cta-optimizer",
    slug: "cta-optimizer",
    title: "CTA Conversion Lab",
    description: "Transform weak calls-to-action into high-converting prompts with urgency and benefit framing.",
    category: "Conversion",
    icon: MousePointerClick,
    href: "/ai/cta-optimizer",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-cta-optimizer",
    primaryField: "content",
    placeholder: "Paste your content with its current CTA — we'll optimize it for conversions…",
  },
  {
    id: "emotion-optimizer",
    slug: "emotion",
    title: "Emotion Amplifier",
    description: "Analyze and boost emotional resonance — map the feeling arc to maximize audience connection.",
    category: "Optimization",
    icon: Heart,
    href: "/ai/emotion",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "auto-reply",
    slug: "auto-reply",
    title: "Smart Reply Engine",
    description: "Generate contextual responses to comments, DMs, and mentions that match your brand voice.",
    category: "Engagement",
    icon: MessageCircle,
    href: "/ai/auto-reply",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },

  // ===== LAYER 3: Strategy & Planning =====
  {
    id: "audience-persona",
    slug: "personas",
    title: "Persona Builder",
    description: "Generate data-driven audience personas with demographics, pain points, and content preferences.",
    category: "Strategy",
    icon: Target,
    href: "/ai/personas",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "smart-campaign",
    slug: "campaigns",
    title: "Campaign Architect",
    description: "Plan end-to-end multi-platform campaigns with content calendars, assets, and KPIs.",
    category: "Campaigns",
    icon: Megaphone,
    href: "/ai/campaigns",
    badge: "Pro",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "strategic-planner",
    slug: "strategic-planner",
    title: "90-Day Content Strategist",
    description: "Build a comprehensive multi-month content roadmap aligned with business goals and growth targets.",
    category: "Strategy",
    icon: Lightbulb,
    href: "/ai/strategic-planner",
    modelLabel: `${base}-pro`,
    runner: "generic",
    functionName: "ai-strategic-planner",
    primaryField: "prompt",
    placeholder: "Describe your business, niche, audience, goals, and constraints…",
  },
  {
    id: "content-recommendations",
    slug: "content-recommendations",
    title: "Next Post Recommender",
    description: "Get AI-powered suggestions for what to post next based on your history, trends, and goals.",
    category: "Strategy",
    icon: Newspaper,
    href: "/ai/content-recommendations",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-content-recommendations",
    primaryField: "content",
    placeholder: "Describe your recent content themes, goals, and audience — or leave blank for general recs…",
  },
  {
    id: "content-intent",
    slug: "content-intent",
    title: "Intent Analyzer",
    description: "Classify content purpose (awareness, conversion, authority) and map its funnel position.",
    category: "Content Intelligence",
    icon: Scan,
    href: "/ai/content-intent",
    badge: "New",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-content-intent",
    primaryField: "content",
    placeholder: "Paste your content to analyze its strategic intent and audience fit…",
  },

  // ===== LAYER 4: Quality & Scoring =====
  {
    id: "quality-scorer",
    slug: "quality-scorer",
    title: "Pre-Publish Quality Score",
    description: "Score content 1-100 across 7 dimensions (hook, clarity, value, emotion, CTA, platform fit, shareability).",
    category: "Quality Assurance",
    icon: Gauge,
    href: "/ai/quality-scorer",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-quality-scorer",
    primaryField: "content",
    placeholder: "Paste your draft content for a comprehensive quality assessment before publishing…",
  },
  {
    id: "predictive-scoring",
    slug: "predictive-scoring",
    title: "Viral Probability Predictor",
    description: "Forecast expected views, likes, shares, and engagement rate before you hit publish.",
    category: "Predictive Analytics",
    icon: BarChart3,
    href: "/ai/predictive-scoring",
    badge: "New",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-predictive-scoring",
    primaryField: "content",
    placeholder: "Paste your content to predict its performance across platforms…",
  },
  {
    id: "content-decay",
    slug: "content-decay",
    title: "Content Decay Detector",
    description: "Predict when evergreen content will lose relevance and get an auto-generated refresh plan.",
    category: "Content Lifecycle",
    icon: TrendingDown,
    href: "/ai/content-decay",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-content-decay",
    primaryField: "content",
    placeholder: "Paste older content to analyze its decay trajectory and get refresh recommendations…",
  },

  // ===== LAYER 5: Repurposing & Formats =====
  {
    id: "format-generator",
    slug: "format-generator",
    title: "Multi-Format Converter",
    description: "Turn one idea into threads, carousels, reels scripts, blog posts, and newsletters simultaneously.",
    category: "Repurposing",
    icon: LayoutGrid,
    href: "/ai/format-generator",
    modelLabel: `${base}-pro`,
    runner: "generic",
    functionName: "ai-format-generator",
    primaryField: "content",
    placeholder: "Paste your core content — we'll generate it in 6+ platform-native formats…",
  },
  {
    id: "carousel-intelligence",
    slug: "carousel-intelligence",
    title: "Carousel Designer",
    description: "Generate slide-by-slide carousel copy with hooks, transitions, and closing CTAs.",
    category: "Visual Content",
    icon: Layers,
    href: "/ai/carousel-intelligence",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-carousel-intelligence",
    primaryField: "content",
    placeholder: "Paste your topic or content — we'll structure it into a high-engagement carousel…",
  },
  {
    id: "podcast-repurposer",
    slug: "podcast-repurposer",
    title: "Podcast Content Extractor",
    description: "Turn a full episode transcript into social clips, blog posts, quote cards, and show notes.",
    category: "Repurposing",
    icon: BookOpen,
    href: "/ai/podcast-repurposer",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-podcast-repurposer",
    primaryField: "transcript",
    placeholder: "Paste your full podcast episode transcript…",
  },
  {
    id: "voice-to-content",
    slug: "voice-to-content",
    title: "Voice Note Publisher",
    description: "Transform raw voice note transcripts into polished, structured social media content.",
    category: "Audio-to-Content",
    icon: MicVocal,
    href: "/ai/voice-to-content",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-voice-to-content",
    primaryField: "transcript",
    placeholder: "Paste your voice note transcript — we'll polish it into publish-ready content…",
  },

  // ===== LAYER 6: Vision & Multimodal =====
  {
    id: "vision",
    slug: "vision",
    title: "AI Image Analyzer",
    description: "Extract insights, generate captions, and identify brand elements from any image.",
    category: "Vision",
    icon: Eye,
    href: "/ai/vision",
    badge: "Popular",
    modelLabel: `${base}-pro`,
    runner: "custom",
  },
  {
    id: "video-understanding",
    slug: "video-understanding",
    title: "Video Intelligence",
    description: "Analyze video content for key moments, sentiment shifts, and repurposing opportunities.",
    category: "Vision",
    icon: Video,
    href: "/ai/video-understanding",
    badge: "New",
    modelLabel: `${base}-pro`,
    runner: "generic",
    functionName: "ai-video-understanding",
    primaryField: "prompt",
    placeholder: "Describe the video content, provide a link, or paste the transcript…",
  },
  {
    id: "screenshot-to-content",
    slug: "screenshot-to-content",
    title: "Screenshot to Post",
    description: "Upload a screenshot of any content and get a fully written social post inspired by it.",
    category: "Vision",
    icon: Camera,
    href: "/ai/screenshot-to-content",
    modelLabel: `${base}-pro`,
    runner: "generic",
    functionName: "ai-screenshot-to-content",
    primaryField: "prompt",
    placeholder: "Describe the screenshot or provide the image URL in advanced mode…",
  },

  // ===== LAYER 7: Audio & Speech =====
  {
    id: "speech-to-text",
    slug: "speech-to-text",
    title: "Speech Transcriber",
    description: "Transcribe audio and video files into accurate, timestamped text.",
    category: "Audio",
    icon: Mic,
    href: "/ai/speech-to-text",
    modelLabel: "(via AI gateway)",
    runner: "custom",
  },
  {
    id: "text-to-speech",
    slug: "text-to-speech",
    title: "AI Voice Generator",
    description: "Convert written content into natural-sounding voiceovers for reels and podcasts.",
    category: "Audio",
    icon: Volume2,
    href: "/ai/text-to-speech",
    modelLabel: "(via AI gateway)",
    runner: "custom",
  },

  // ===== LAYER 8: Multilingual & Localization =====
  {
    id: "multilingual",
    slug: "multilingual",
    title: "Global Translator",
    description: "Translate and culturally adapt content for 50+ languages while preserving brand voice.",
    category: "Multilingual",
    icon: Globe,
    href: "/ai/multilingual",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "cultural-localization",
    slug: "cultural-localization",
    title: "Cultural Adapter",
    description: "Adapt idioms, humor, references, and social norms for a target culture — not just translate.",
    category: "Localization",
    icon: Flag,
    href: "/ai/cultural-localization",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-cultural-localization",
    primaryField: "content",
    placeholder: "Paste content + specify target culture/region in advanced options…",
  },
  {
    id: "region-optimizer",
    slug: "region-optimizer",
    title: "Regional SEO Optimizer",
    description: "Optimize content for local search, regional hashtags, and geo-specific engagement patterns.",
    category: "Localization",
    icon: MapPin,
    href: "/ai/region-optimizer",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-region-optimizer",
    primaryField: "content",
    placeholder: "Paste content + specify the target region for optimization…",
  },
  {
    id: "global-brand-voice",
    slug: "global-brand-voice",
    title: "Cross-Market Brand Guard",
    description: "Ensure brand voice consistency across all languages and regional adaptations.",
    category: "Brand Identity",
    icon: Languages,
    href: "/ai/global-brand-voice",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-global-brand-voice",
    primaryField: "content",
    placeholder: "Paste translated/localized content to verify brand voice consistency…",
  },

  // ===== LAYER 9: Safety & Compliance =====
  {
    id: "content-moderation",
    slug: "moderation",
    title: "Content Safety Scanner",
    description: "Detect policy violations, brand risks, and offensive content before publishing.",
    category: "Safety",
    icon: Shield,
    href: "/ai/moderation",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "pre-publish-safety",
    slug: "pre-publish-safety",
    title: "Pre-Publish Compliance Check",
    description: "Final legal, regulatory, and platform ToS review — catch issues before they go live.",
    category: "Compliance",
    icon: ShieldCheck,
    href: "/ai/pre-publish-safety",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-pre-publish-safety",
    primaryField: "content",
    placeholder: "Paste your final draft for compliance and safety review…",
  },
  {
    id: "brand-guardrails",
    slug: "brand-guardrails",
    title: "Brand Rule Enforcer",
    description: "Check content against custom brand rules, forbidden phrases, and competitor mentions.",
    category: "Brand Protection",
    icon: ShieldAlert,
    href: "/ai/brand-guardrails",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-brand-guardrails",
    primaryField: "content",
    placeholder: "Paste content to check against your brand guidelines and forbidden terms…",
  },

  // ===== LAYER 10: Research & Trends =====
  {
    id: "trend-mining",
    slug: "trends",
    title: "Trend Radar",
    description: "Surface emerging trends, viral patterns, and niche opportunities in real-time.",
    category: "Research",
    icon: TrendingUp,
    href: "/ai/trends",
    badge: "Hot",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "seasonal-intelligence",
    slug: "seasonal-intelligence",
    title: "Seasonal Content Calendar",
    description: "Get AI-generated content angles tied to holidays, events, and seasonal trends.",
    category: "Calendar Planning",
    icon: Calendar,
    href: "/ai/seasonal-intelligence",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-seasonal-intelligence",
    primaryField: "content",
    placeholder: "Describe your niche — we'll map seasonal hooks and calendar opportunities…",
  },
  {
    id: "content-knowledge-graph",
    slug: "content-knowledge-graph",
    title: "Topic Relationship Mapper",
    description: "Extract entities, map topic clusters, and discover content pillar opportunities.",
    category: "Content Intelligence",
    icon: Network,
    href: "/ai/content-knowledge-graph",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-content-knowledge-graph",
    primaryField: "content",
    placeholder: "Paste your content library topics or a long-form piece to map relationships…",
  },

  // ===== LAYER 11: Revenue & Partnerships =====
  {
    id: "content-monetizer",
    slug: "monetize",
    title: "Monetization Strategist",
    description: "Identify revenue angles — sponsorships, affiliates, digital products, and paid community fits.",
    category: "Revenue",
    icon: DollarSign,
    href: "/ai/monetize",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "influencer-matcher",
    slug: "influencers",
    title: "Influencer Scout",
    description: "Find, evaluate, and plan collaborations with niche-relevant creators at any follower tier.",
    category: "Partnerships",
    icon: Handshake,
    href: "/ai/influencers",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },

  // ===== LAYER 12: Accessibility =====
  {
    id: "accessibility",
    slug: "accessibility",
    title: "Accessibility Enhancer",
    description: "Generate alt text, captions, reading-level adjustments, and WCAG-compliant content.",
    category: "Accessibility",
    icon: Accessibility,
    href: "/ai/accessibility",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },

  // ===== LAYER 13: Automation & Workflows =====
  {
    id: "autonomous-agent",
    slug: "autonomous-agent",
    title: "AI Content Agent",
    description: "Delegate a full content task — the agent plans, drafts, reviews, and delivers autonomously.",
    category: "Automation",
    icon: Bot,
    href: "/ai/autonomous-agent",
    badge: "Pro",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-autonomous-agent",
    primaryField: "prompt",
    placeholder: "Describe the content task you want the agent to complete end-to-end…",
  },
  {
    id: "workflow-builder",
    slug: "workflow-builder",
    title: "Content Pipeline Designer",
    description: "Design repeatable content workflows with stages, checkpoints, and automation triggers.",
    category: "Automation",
    icon: GitBranch,
    href: "/ai/workflow-builder",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-workflow-builder",
    primaryField: "prompt",
    placeholder: "Describe your ideal content production pipeline — from ideation to publishing…",
  },
  {
    id: "self-healing",
    slug: "self-healing",
    title: "Content System Debugger",
    description: "Diagnose broken content workflows, inconsistent output, and production bottlenecks.",
    category: "Operations",
    icon: RefreshCcw,
    href: "/ai/self-healing",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-self-healing",
    primaryField: "prompt",
    placeholder: "Describe the content system issue you're experiencing…",
  },

  // ===== LAYER 14: Enterprise & Multi-Brand =====
  {
    id: "multi-brand",
    slug: "multi-brand",
    title: "Multi-Brand Content Engine",
    description: "Generate distinct content variants for multiple brands from a single brief.",
    category: "Enterprise",
    icon: SquareStack,
    href: "/ai/multi-brand",
    badge: "Pro",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-multi-brand",
    primaryField: "content",
    placeholder: "Paste your content brief — specify brand names and voice guidelines in advanced options…",
  },
  {
    id: "content-memory",
    slug: "content-memory",
    title: "Brand Memory Vault",
    description: "Store and recall reusable facts, preferences, and brand context across sessions.",
    category: "Knowledge Base",
    icon: HardDrive,
    href: "/ai/content-memory",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-content-memory",
    primaryField: "prompt",
    placeholder: "Store a fact: 'Our brand color is midnight blue' or ask: 'What's our target audience?'…",
  },
];
