import type { LucideIcon } from "lucide-react";
import {
  Accessibility,
  Brain,
  DollarSign,
  Eye,
  Globe,
  Handshake,
  Heart,
  Mic,
  MessageCircle,
  Shield,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Volume2,
  Wand2,
  Zap,
  Layers,
  Workflow,
  Wrench,
  BookOpen,
  Film,
  Image,
  LayoutGrid,
  Map,
  Flag,
  BadgeCheck,
  Scan,
  BarChart3,
  Lightbulb,
  Network,
  Calendar,
  Database,
} from "lucide-react";

export type AiToolRunner = "custom" | "generic";

export interface AiToolDefinition {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  icon: LucideIcon;
  href: string;
  badge?: "New" | "Hot" | "Pro" | "Popular";
  modelLabel?: string;
  runner: AiToolRunner;
  functionName?: string;
  primaryField?: string;
  placeholder?: string;
}

const base = "google/gemini-2.5";

export const aiToolsCatalog: AiToolDefinition[] = [
  // ===== Existing UI pages (16) =====
  {
    id: "vision",
    slug: "vision",
    title: "AI Vision",
    description: "Analyze images and generate insights/captions.",
    category: "Vision",
    icon: Eye,
    href: "/ai/vision",
    badge: "Popular",
    modelLabel: `${base}-pro` ,
    runner: "custom",
  },
  {
    id: "speech-to-text",
    slug: "speech-to-text",
    title: "Speech to Text",
    description: "Transcribe audio/video into text.",
    category: "Audio",
    icon: Mic,
    href: "/ai/speech-to-text",
    modelLabel: "(via AI gateway)",
    runner: "custom",
  },
  {
    id: "text-to-speech",
    slug: "text-to-speech",
    title: "Text to Speech",
    description: "Convert text into natural-sounding speech.",
    category: "Audio",
    icon: Volume2,
    href: "/ai/text-to-speech",
    modelLabel: "(via AI gateway)",
    runner: "custom",
  },
  {
    id: "reasoning",
    slug: "reasoning",
    title: "AI Reasoning",
    description: "Deep analysis and strategic reasoning.",
    category: "Reasoning",
    icon: Brain,
    href: "/ai/reasoning",
    badge: "New",
    modelLabel: `${base}-flash / pro`,
    runner: "custom",
  },
  {
    id: "multilingual",
    slug: "multilingual",
    title: "Multilingual AI",
    description: "Translate and adapt content for global audiences.",
    category: "Language",
    icon: Globe,
    href: "/ai/multilingual",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "content-moderation",
    slug: "moderation",
    title: "Content Moderation",
    description: "Brand-safety checks and policy-aware rewriting.",
    category: "Safety",
    icon: Shield,
    href: "/ai/moderation",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "trend-mining",
    slug: "trends",
    title: "Trend Mining",
    description: "Discover trends and content angles.",
    category: "Research",
    icon: TrendingUp,
    href: "/ai/trends",
    badge: "Hot",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "brand-voice",
    slug: "brand-voice",
    title: "Brand Voice",
    description: "Create content in your brand's voice.",
    category: "Branding",
    icon: Sparkles,
    href: "/ai/brand-voice",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "audience-persona",
    slug: "personas",
    title: "Audience Persona",
    description: "Generate detailed audience personas.",
    category: "Strategy",
    icon: Target,
    href: "/ai/personas",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "smart-campaign",
    slug: "campaigns",
    title: "Smart Campaign",
    description: "Multi-platform campaign planning and assets.",
    category: "Campaigns",
    icon: Target,
    href: "/ai/campaigns",
    badge: "Pro",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "auto-reply",
    slug: "auto-reply",
    title: "Auto Reply",
    description: "Generate responses to comments/DMs.",
    category: "Engagement",
    icon: MessageCircle,
    href: "/ai/auto-reply",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "emotion-optimizer",
    slug: "emotion",
    title: "Emotion Optimizer",
    description: "Improve emotional resonance and engagement.",
    category: "Optimization",
    icon: Heart,
    href: "/ai/emotion",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "viral-hooks",
    slug: "hooks",
    title: "Viral Hooks",
    description: "Generate scroll-stopping hooks.",
    category: "Content",
    icon: Zap,
    href: "/ai/hooks",
    badge: "Hot",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "influencer-matcher",
    slug: "influencers",
    title: "Influencer Matcher",
    description: "Find and evaluate influencer partners.",
    category: "Partnerships",
    icon: Handshake,
    href: "/ai/influencers",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "content-monetizer",
    slug: "monetize",
    title: "Content Monetizer",
    description: "Monetization angles and sponsorship fit.",
    category: "Revenue",
    icon: DollarSign,
    href: "/ai/monetize",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },
  {
    id: "accessibility",
    slug: "accessibility",
    title: "Accessibility",
    description: "Alt text, captions, and accessibility upgrades.",
    category: "Accessibility",
    icon: Accessibility,
    href: "/ai/accessibility",
    modelLabel: `${base}-flash`,
    runner: "custom",
  },

  // ===== Missing UI pages -> Generic runner (20) =====
  {
    id: "content-intent",
    slug: "content-intent",
    title: "Content Intent",
    description: "Detect intent, audience fit, and CTA alignment.",
    category: "Content Intelligence",
    icon: Scan,
    href: "/ai/content-intent",
    badge: "New",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-content-intent",
    primaryField: "content",
    placeholder: "Paste your content here…",
  },
  {
    id: "performance-reasoner",
    slug: "performance-reasoner",
    title: "Performance Reasoner",
    description: "Explain performance and suggest improvements.",
    category: "Analytics",
    icon: BarChart3,
    href: "/ai/performance-reasoner",
    modelLabel: `${base}-pro`,
    runner: "generic",
    functionName: "ai-performance-reasoner",
    primaryField: "content",
    placeholder: "Paste post + metrics/context…",
  },
  {
    id: "content-decay",
    slug: "content-decay",
    title: "Content Decay",
    description: "Predict when content will decay and how to refresh it.",
    category: "Optimization",
    icon: Calendar,
    href: "/ai/content-decay",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-content-decay",
    primaryField: "content",
  },
  {
    id: "quality-scorer",
    slug: "quality-scorer",
    title: "Quality Scorer",
    description: "Score and improve content quality.",
    category: "Quality",
    icon: BadgeCheck,
    href: "/ai/quality-scorer",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-quality-scorer",
    primaryField: "content",
  },
  {
    id: "strategic-planner",
    slug: "strategic-planner",
    title: "Strategic Planner",
    description: "Create a multi-step content strategy plan.",
    category: "Strategy",
    icon: Lightbulb,
    href: "/ai/strategic-planner",
    modelLabel: `${base}-pro`,
    runner: "generic",
    functionName: "ai-strategic-planner",
    primaryField: "prompt",
    placeholder: "Describe your goal, niche, audience, constraints…",
  },
  {
    id: "format-generator",
    slug: "format-generator",
    title: "Format Generator",
    description: "Turn one idea into multiple platform formats.",
    category: "Repurposing",
    icon: LayoutGrid,
    href: "/ai/format-generator",
    modelLabel: `${base}-pro`,
    runner: "generic",
    functionName: "ai-format-generator",
    primaryField: "content",
  },
  {
    id: "tone-personality",
    slug: "tone-personality",
    title: "Tone & Personality",
    description: "Rewrite content with a chosen personality/tone.",
    category: "Branding",
    icon: Sparkles,
    href: "/ai/tone-personality",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-tone-personality",
    primaryField: "content",
  },
  {
    id: "audience-writer",
    slug: "audience-writer",
    title: "Audience Writer",
    description: "Rewrite for a specific audience segment.",
    category: "Audience",
    icon: Users,
    href: "/ai/audience-writer",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-audience-writer",
    primaryField: "content",
  },
  {
    id: "hook-lab",
    slug: "hook-lab",
    title: "Hook Lab",
    description: "Generate many hook variations and angles.",
    category: "Content",
    icon: Zap,
    href: "/ai/hook-lab",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-hook-lab",
    primaryField: "topic",
    placeholder: "What is the post/video about?",
  },
  {
    id: "cta-optimizer",
    slug: "cta-optimizer",
    title: "CTA Optimizer",
    description: "Improve call-to-action and conversion messaging.",
    category: "Conversion",
    icon: Target,
    href: "/ai/cta-optimizer",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-cta-optimizer",
    primaryField: "content",
  },
  {
    id: "autonomous-agent",
    slug: "autonomous-agent",
    title: "Autonomous Agent",
    description: "Plan and execute a content task step-by-step.",
    category: "Automation",
    icon: Wrench,
    href: "/ai/autonomous-agent",
    badge: "Pro",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-autonomous-agent",
    primaryField: "prompt",
  },
  {
    id: "workflow-builder",
    slug: "workflow-builder",
    title: "Workflow Builder",
    description: "Design repeatable content workflows.",
    category: "Automation",
    icon: Workflow,
    href: "/ai/workflow-builder",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-workflow-builder",
    primaryField: "prompt",
  },
  {
    id: "self-healing",
    slug: "self-healing",
    title: "Self-Healing",
    description: "Diagnose and propose fixes for content systems.",
    category: "Automation",
    icon: Wrench,
    href: "/ai/self-healing",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-self-healing",
    primaryField: "prompt",
  },
  {
    id: "voice-to-content",
    slug: "voice-to-content",
    title: "Voice to Content",
    description: "Turn spoken ideas into structured content.",
    category: "Audio",
    icon: Mic,
    href: "/ai/voice-to-content",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-voice-to-content",
    primaryField: "transcript",
    placeholder: "Paste transcript…",
  },
  {
    id: "podcast-repurposer",
    slug: "podcast-repurposer",
    title: "Podcast Repurposer",
    description: "Convert podcast transcript into a full content pack.",
    category: "Repurposing",
    icon: BookOpen,
    href: "/ai/podcast-repurposer",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-podcast-repurposer",
    primaryField: "transcript",
    placeholder: "Paste full episode transcript…",
  },
  {
    id: "video-understanding",
    slug: "video-understanding",
    title: "Video Understanding",
    description: "Analyze video and extract insights (provide details/links in advanced mode).",
    category: "Vision",
    icon: Film,
    href: "/ai/video-understanding",
    badge: "New",
    modelLabel: `${base}-pro`,
    runner: "generic",
    functionName: "ai-video-understanding",
    primaryField: "prompt",
  },
  {
    id: "screenshot-to-content",
    slug: "screenshot-to-content",
    title: "Screenshot to Content",
    description: "Turn screenshots into posts (use advanced mode for image URLs).",
    category: "Vision",
    icon: Image,
    href: "/ai/screenshot-to-content",
    modelLabel: `${base}-pro`,
    runner: "generic",
    functionName: "ai-screenshot-to-content",
    primaryField: "prompt",
  },
  {
    id: "carousel-intelligence",
    slug: "carousel-intelligence",
    title: "Carousel Intelligence",
    description: "Generate carousel structure and slide copy.",
    category: "Content",
    icon: Layers,
    href: "/ai/carousel-intelligence",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-carousel-intelligence",
    primaryField: "content",
  },
  {
    id: "cultural-localization",
    slug: "cultural-localization",
    title: "Cultural Localization",
    description: "Adapt content culturally for a target audience.",
    category: "Localization",
    icon: Flag,
    href: "/ai/cultural-localization",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-cultural-localization",
    primaryField: "content",
  },
  {
    id: "region-optimizer",
    slug: "region-optimizer",
    title: "Region Optimizer",
    description: "Optimize content for a specific region.",
    category: "Localization",
    icon: Map,
    href: "/ai/region-optimizer",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-region-optimizer",
    primaryField: "content",
  },
  {
    id: "global-brand-voice",
    slug: "global-brand-voice",
    title: "Global Brand Voice",
    description: "Keep brand voice consistent across languages and regions.",
    category: "Branding",
    icon: Globe,
    href: "/ai/global-brand-voice",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-global-brand-voice",
    primaryField: "content",
  },
  {
    id: "pre-publish-safety",
    slug: "pre-publish-safety",
    title: "Pre‑Publish Safety",
    description: "Final safety + compliance review before posting.",
    category: "Safety",
    icon: Shield,
    href: "/ai/pre-publish-safety",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-pre-publish-safety",
    primaryField: "content",
  },
  {
    id: "brand-guardrails",
    slug: "brand-guardrails",
    title: "Brand Guardrails",
    description: "Enforce brand rules and forbidden phrases.",
    category: "Safety",
    icon: Shield,
    href: "/ai/brand-guardrails",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-brand-guardrails",
    primaryField: "content",
  },
  {
    id: "engagement-reasoner",
    slug: "engagement-reasoner",
    title: "Engagement Reasoner",
    description: "Explain engagement drivers and improvements.",
    category: "Analytics",
    icon: MessageCircle,
    href: "/ai/engagement-reasoner",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-engagement-reasoner",
    primaryField: "content",
  },
  {
    id: "predictive-scoring",
    slug: "predictive-scoring",
    title: "Predictive Scoring",
    description: "Predict performance and suggest optimizations.",
    category: "Analytics",
    icon: BarChart3,
    href: "/ai/predictive-scoring",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-predictive-scoring",
    primaryField: "content",
  },
  {
    id: "content-recommendations",
    slug: "content-recommendations",
    title: "Content Recommendations",
    description: "Recommend next posts based on goals and content.",
    category: "Strategy",
    icon: Lightbulb,
    href: "/ai/content-recommendations",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-content-recommendations",
    primaryField: "content",
  },
  {
    id: "multi-brand",
    slug: "multi-brand",
    title: "Multi‑Brand",
    description: "Generate variants for multiple brands.",
    category: "Branding",
    icon: Layers,
    href: "/ai/multi-brand",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-multi-brand",
    primaryField: "content",
  },
  {
    id: "content-knowledge-graph",
    slug: "content-knowledge-graph",
    title: "Content Knowledge Graph",
    description: "Extract entities/topics and map relationships.",
    category: "Content Intelligence",
    icon: Network,
    href: "/ai/content-knowledge-graph",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-content-knowledge-graph",
    primaryField: "content",
  },
  {
    id: "seasonal-intelligence",
    slug: "seasonal-intelligence",
    title: "Seasonal Intelligence",
    description: "Seasonal angles, calendar hooks, and timing.",
    category: "Research",
    icon: Calendar,
    href: "/ai/seasonal-intelligence",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-seasonal-intelligence",
    primaryField: "content",
  },
  {
    id: "content-memory",
    slug: "content-memory",
    title: "Content Memory",
    description: "Store/recall reusable facts and preferences (use advanced mode).",
    category: "Memory",
    icon: Database,
    href: "/ai/content-memory",
    modelLabel: `${base}-flash`,
    runner: "generic",
    functionName: "ai-content-memory",
    primaryField: "prompt",
  },
];
